/** @format */
import Head from 'next/head';

import { Button } from '@mantine/core';

export default function Home() {
  return (
    <>
      <Head>
        <title>Infiviz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-testid="main">
        <Button type="button">Hello</Button>
      </main>
    </>
  );
}
